const express = require('express');
const cors = require('cors');
const dotenv = require('dotenv');
const mongoose = require('mongoose');
const cookieParser = require('cookie-parser');
const db = require('./config/db/index');
const router = require('./routes/index');
const app = express();
const port = 3000;
app.use(cors());
app.use(cookieParser());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
db.connect();
router(app);
app.listen(port);
